# ─── Current Azure Client (for RBAC assignments) ─────────────────────────────
data "azurerm_client_config" "current" {}

# ─── Generate SSH Key Pair (RSA 4096) ────────────────────────────────────────
resource "tls_private_key" "generated" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# ─── Resource Group ───────────────────────────────────────────────────────────
resource "azurerm_resource_group" "rg" {
  location = var.location_centralindia
  name     = var.resource_group_name
  tags     = {}
}

# ─── SSH Public Keys (stored in Azure, generated by tls_private_key) ──────────
/*
resource "azurerm_ssh_public_key" "ssh_key_usa" {
  location            = var.location_westus2
  name                = var.ssh_public_key_resource_name
  public_key          = tls_private_key.generated.public_key_openssh
  resource_group_name = azurerm_resource_group.rg.name
  tags                = {}
}
*/

resource "azurerm_ssh_public_key" "ssh_key_india" {
  location            = var.location_centralindia
  name                = var.ssh_public_key_india_resource_name
  public_key          = tls_private_key.generated.public_key_openssh
  resource_group_name = azurerm_resource_group.rg.name
  tags                = {}
}

# ─── Virtual Networks ─────────────────────────────────────────────────────────
resource "azurerm_virtual_network" "vnet_india" {
  address_space       = var.vnet_address_space
  location            = var.location_centralindia
  name                = var.vnet_india_name
  resource_group_name = azurerm_resource_group.rg.name
  tags                = {}
}

/*
resource "azurerm_virtual_network" "vnet_usa" {
  address_space       = var.vnet_address_space
  location            = var.location_westus2
  name                = var.vnet_westus2_name
  resource_group_name = azurerm_resource_group.rg.name
  tags                = {}
}
*/

# ─── Subnets (standalone — no inline subnet block in VNet above) ──────────────
resource "azurerm_subnet" "subnet_india" {
  address_prefixes                              = var.subnet_address_prefixes
  default_outbound_access_enabled               = true
  name                                          = "default"
  private_endpoint_network_policies             = "Disabled"
  private_link_service_network_policies_enabled = true
  resource_group_name                           = azurerm_resource_group.rg.name
  virtual_network_name                          = azurerm_virtual_network.vnet_india.name
}

/*
resource "azurerm_subnet" "subnet_usa" {
  address_prefixes                              = var.subnet_address_prefixes
  default_outbound_access_enabled               = true
  name                                          = "default"
  private_endpoint_network_policies             = "Disabled"
  private_link_service_network_policies_enabled = true
  resource_group_name                           = azurerm_resource_group.rg.name
  virtual_network_name                          = azurerm_virtual_network.vnet_usa.name
}
*/

# ─── Public IPs ───────────────────────────────────────────────────────────────
resource "azurerm_public_ip" "pip_india" {
  allocation_method       = "Static"
  idle_timeout_in_minutes = 4
  ip_version              = "IPv4"
  location                = var.location_centralindia
  name                    = var.public_ip_india_name
  resource_group_name     = azurerm_resource_group.rg.name
  sku                     = "Standard"
  sku_tier                = "Regional"
  tags                    = {}
  # zones = ["1"]
  # STUDENT SUBSCRIPTION: Availability Zones are not supported.
  # Uncomment when upgrading to a paid subscription.
}

/*
resource "azurerm_public_ip" "pip_usa" {
  allocation_method       = "Static"
  idle_timeout_in_minutes = 4
  ip_version              = "IPv4"
  location                = var.location_westus2
  name                    = var.public_ip_westus2_name
  resource_group_name     = azurerm_resource_group.rg.name
  sku                     = "Standard"
  sku_tier                = "Regional"
  tags                    = {}
  # zones = ["2"]
  # STUDENT SUBSCRIPTION: Availability Zones are not supported.
  # Uncomment when upgrading to a paid subscription.
}
*/

# ─── NSG — Central India ──────────────────────────────────────────────────────
resource "azurerm_network_security_group" "nsg_india" {
  location            = var.location_centralindia
  name                = var.nsg_india_name
  resource_group_name = azurerm_resource_group.rg.name
  tags                = {}
}

resource "azurerm_network_security_rule" "ssh_india" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "22"
  direction                   = "Inbound"
  name                        = "SSH"
  network_security_group_name = azurerm_network_security_group.nsg_india.name
  priority                    = 300
  protocol                    = "Tcp"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}

resource "azurerm_network_security_rule" "https_india" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "443"
  direction                   = "Inbound"
  name                        = "HTTPS"
  network_security_group_name = azurerm_network_security_group.nsg_india.name
  priority                    = 320
  protocol                    = "Tcp"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}

resource "azurerm_network_security_rule" "http_india" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "80"
  direction                   = "Inbound"
  name                        = "HTTP"
  network_security_group_name = azurerm_network_security_group.nsg_india.name
  priority                    = 340
  protocol                    = "Tcp"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}

resource "azurerm_network_security_rule" "client_portal_india" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "5173"
  direction                   = "Inbound"
  name                        = "client-portal-app"
  network_security_group_name = azurerm_network_security_group.nsg_india.name
  priority                    = 360
  protocol                    = "*"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}

resource "azurerm_network_security_rule" "service_provider_india" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "8080"
  direction                   = "Inbound"
  name                        = "service-provider-platform"
  network_security_group_name = azurerm_network_security_group.nsg_india.name
  priority                    = 350
  protocol                    = "Tcp"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}

resource "azurerm_network_security_rule" "admin_portal_india" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "8081"
  direction                   = "Inbound"
  name                        = "admin-portal"
  network_security_group_name = azurerm_network_security_group.nsg_india.name
  priority                    = 370
  protocol                    = "*"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}

resource "azurerm_network_security_rule" "admin_portal_ui_india" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "8181"
  direction                   = "Inbound"
  name                        = "admin-portal-ui"
  network_security_group_name = azurerm_network_security_group.nsg_india.name
  priority                    = 380
  protocol                    = "*"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}

# ─── NSG — West US 2 ──────────────────────────────────────────────────────────
/*
resource "azurerm_network_security_group" "nsg_usa" {
  location            = var.location_westus2
  name                = var.nsg_westus2_name
  resource_group_name = azurerm_resource_group.rg.name
  tags                = {}
}

resource "azurerm_network_security_rule" "ssh_usa" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "22"
  direction                   = "Inbound"
  name                        = "SSH"
  network_security_group_name = azurerm_network_security_group.nsg_usa.name
  priority                    = 300
  protocol                    = "Tcp"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}

resource "azurerm_network_security_rule" "https_usa" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "443"
  direction                   = "Inbound"
  name                        = "HTTPS"
  network_security_group_name = azurerm_network_security_group.nsg_usa.name
  priority                    = 320
  protocol                    = "Tcp"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}

resource "azurerm_network_security_rule" "client_portal_usa" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "5173"
  direction                   = "Inbound"
  name                        = "client-portal-http"
  network_security_group_name = azurerm_network_security_group.nsg_usa.name
  priority                    = 330
  protocol                    = "Tcp"
  resource_group_name         = azurerm_resource_group.rg.name
  source_address_prefix       = "*"
  source_port_range           = "*"
}
*/

# ─── Network Interfaces ───────────────────────────────────────────────────────
resource "azurerm_network_interface" "nic_india" {
  # accelerated_networking_enabled = true
  # STUDENT SUBSCRIPTION: Accelerated Networking is not supported on B-series VMs.
  # Uncomment when using D-series or above on a paid subscription.
  accelerated_networking_enabled = false
  location                       = var.location_centralindia
  name                           = var.nic_india_name
  resource_group_name            = azurerm_resource_group.rg.name
  tags                           = {}

  ip_configuration {
    name                          = "ipconfig1"
    primary                       = true
    private_ip_address_allocation = "Dynamic"
    private_ip_address_version    = "IPv4"
    public_ip_address_id          = azurerm_public_ip.pip_india.id
    subnet_id                     = azurerm_subnet.subnet_india.id
  }
}

resource "azurerm_network_interface_security_group_association" "nic_india_nsg" {
  network_interface_id      = azurerm_network_interface.nic_india.id
  network_security_group_id = azurerm_network_security_group.nsg_india.id
}

/*
resource "azurerm_network_interface" "nic_usa" {
  # accelerated_networking_enabled = true
  # STUDENT SUBSCRIPTION: Accelerated Networking is not supported on B-series VMs.
  # Uncomment when using D-series or above on a paid subscription.
  accelerated_networking_enabled = false
  location                       = var.location_westus2
  name                           = var.nic_westus2_name
  resource_group_name            = azurerm_resource_group.rg.name
  tags                           = {}

  ip_configuration {
    name                          = "ipconfig1"
    primary                       = true
    private_ip_address_allocation = "Dynamic"
    private_ip_address_version    = "IPv4"
    public_ip_address_id          = azurerm_public_ip.pip_usa.id
    subnet_id                     = azurerm_subnet.subnet_usa.id
  }
}

resource "azurerm_network_interface_security_group_association" "nic_usa_nsg" {
  network_interface_id      = azurerm_network_interface.nic_usa.id
  network_security_group_id = azurerm_network_security_group.nsg_usa.id
}
*/

# ─── Key Vault ────────────────────────────────────────────────────────────────
/*
resource "azurerm_key_vault" "kv" {
  rbac_authorization_enabled      = true
  enabled_for_deployment          = true
  enabled_for_disk_encryption     = false
  enabled_for_template_deployment = false
  location                        = var.location_westus2
  name                            = var.key_vault_name
  public_network_access_enabled   = true
  purge_protection_enabled        = false
  resource_group_name             = azurerm_resource_group.rg.name
  sku_name                        = var.key_vault_sku
  soft_delete_retention_days      = var.key_vault_soft_delete_days
  tags                            = {}
  tenant_id                       = var.tenant_id

  network_acls {
    bypass         = "AzureServices"
    default_action = "Allow"
  }
}

# ─── RBAC: grant the deploying principal Key Vault Secrets Officer ────────────
# This allows terraform apply to read/write secrets in the vault.
resource "azurerm_role_assignment" "kv_secrets_officer" {
  scope                = azurerm_key_vault.kv.id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = data.azurerm_client_config.current.object_id
}

# ─── Key Vault Secrets ────────────────────────────────────────────────────────
resource "azurerm_key_vault_secret" "ssh_private_key" {
  name         = "ssh-private-key"
  value        = tls_private_key.generated.private_key_pem
  key_vault_id = azurerm_key_vault.kv.id
  content_type = "text/plain"
  tags         = { purpose = "vm-ssh-access" }
  depends_on   = [azurerm_role_assignment.kv_secrets_officer]
}

resource "azurerm_key_vault_secret" "ssh_public_key" {
  name         = "ssh-public-key"
  value        = tls_private_key.generated.public_key_openssh
  key_vault_id = azurerm_key_vault.kv.id
  content_type = "text/plain"
  tags         = { purpose = "vm-ssh-access" }
  depends_on   = [azurerm_role_assignment.kv_secrets_officer]
}

resource "azurerm_key_vault_secret" "admin_username" {
  name         = "admin-username"
  value        = var.admin_username
  key_vault_id = azurerm_key_vault.kv.id
  content_type = "text/plain"
  tags         = { purpose = "vm-recovery-credentials" }
  depends_on   = [azurerm_role_assignment.kv_secrets_officer]
}

resource "azurerm_key_vault_secret" "admin_password" {
  name         = "admin-password"
  value        = var.admin_password
  key_vault_id = azurerm_key_vault.kv.id
  content_type = "text/plain"
  tags         = { purpose = "vm-recovery-credentials" }
  depends_on   = [azurerm_role_assignment.kv_secrets_officer]
}
*/

# ─── Linux VM — West US 2 ────────────────────────────────────────────────────
/*
resource "azurerm_linux_virtual_machine" "vm_usa" {
  admin_password                  = var.admin_password
  admin_username                  = var.admin_username
  allow_extension_operations      = true
  computer_name                   = var.vm_westus2_computer_name
  disable_password_authentication = false # password kept as recovery; primary auth is SSH
  disk_controller_type            = "SCSI"
  extensions_time_budget          = "PT1H30M"
  location                        = var.location_westus2
  name                            = var.vm_westus2_name
  network_interface_ids           = [azurerm_network_interface.nic_usa.id]
  patch_assessment_mode           = "ImageDefault"
  patch_mode                      = "ImageDefault"
  priority                        = "Regular"
  provision_vm_agent              = true
  resource_group_name             = azurerm_resource_group.rg.name
  secure_boot_enabled             = true
  size                            = var.vm_size
  tags                            = {}
  vtpm_enabled                    = true
  # zone = "2"
  # STUDENT SUBSCRIPTION: Availability Zones are not supported.
  # Uncomment when upgrading to a paid subscription.

  additional_capabilities {
    hibernation_enabled = false
    ultra_ssd_enabled   = false
  }

  admin_ssh_key {
    public_key = azurerm_ssh_public_key.ssh_key_usa.public_key
    username   = var.admin_username
  }

  # Empty boot_diagnostics block enables managed-storage boot diagnostics
  boot_diagnostics {}

  os_disk {
    caching              = "ReadWrite"
    disk_size_gb         = var.os_disk_size_gb
    name                 = var.vm_westus2_os_disk_name
    storage_account_type = var.os_disk_storage_type
  }

  source_image_reference {
    offer     = var.image_offer
    publisher = var.image_publisher
    sku       = var.image_sku
    version   = var.image_version
  }

  depends_on = [
    azurerm_network_interface_security_group_association.nic_usa_nsg,
  ]
}
*/

# ─── Linux VM — Central India ─────────────────────────────────────────────────
resource "azurerm_linux_virtual_machine" "vm_india" {
  admin_password                  = var.admin_password
  admin_username                  = var.admin_username
  allow_extension_operations      = true
  computer_name                   = var.vm_india_computer_name
  disable_password_authentication = false # password kept as recovery; primary auth is SSH
  disk_controller_type            = "SCSI"
  extensions_time_budget          = "PT1H30M"
  location                        = var.location_centralindia
  name                            = var.vm_india_name
  network_interface_ids           = [azurerm_network_interface.nic_india.id]
  patch_assessment_mode           = "ImageDefault"
  patch_mode                      = "ImageDefault"
  priority                        = "Regular"
  provision_vm_agent              = true
  resource_group_name             = azurerm_resource_group.rg.name
  secure_boot_enabled             = true
  size                            = var.vm_size
  tags                            = {}
  vtpm_enabled                    = true
  # zone = "1"
  # STUDENT SUBSCRIPTION: Availability Zones are not supported.
  # Uncomment when upgrading to a paid subscription.

  additional_capabilities {
    hibernation_enabled = false
    ultra_ssd_enabled   = false
  }

  admin_ssh_key {
    public_key = azurerm_ssh_public_key.ssh_key_india.public_key
    username   = var.admin_username
  }

  # Empty boot_diagnostics block enables managed-storage boot diagnostics
  boot_diagnostics {}

  identity {
    type = "SystemAssigned"
  }

  os_disk {
    caching              = "ReadWrite"
    disk_size_gb         = var.os_disk_size_gb
    name                 = var.vm_india_os_disk_name
    storage_account_type = var.os_disk_storage_type
  }

  source_image_reference {
    offer     = var.image_offer
    publisher = var.image_publisher
    sku       = var.image_sku
    version   = var.image_version
  }

  depends_on = [
    azurerm_network_interface_security_group_association.nic_india_nsg,
  ]
}

# ─── VM Extensions — Central India ───────────────────────────────────────────

# STUDENT SUBSCRIPTION: AADSSHLoginForLinux requires Azure Active Directory Premium
# (P1 or P2) which is not included in Azure for Students. This extension is
# commented out. Uncomment when using a paid subscription with AAD Premium.
#
# resource "azurerm_virtual_machine_extension" "aad_login_india" {
#   auto_upgrade_minor_version  = true
#   automatic_upgrade_enabled   = false
#   failure_suppression_enabled = false
#   name                        = "AADSSHLoginForLinux"
#   publisher                   = "Microsoft.Azure.ActiveDirectory"
#   tags                        = {}
#   type                        = "AADSSHLoginForLinux"
#   type_handler_version        = "1.0"
#   virtual_machine_id          = azurerm_linux_virtual_machine.vm_india.id
# }

/*
resource "azurerm_virtual_machine_extension" "vm_access_india" {
  auto_upgrade_minor_version  = true
  automatic_upgrade_enabled   = false
  failure_suppression_enabled = false
  name                        = "enablevmAccess"
  publisher                   = "Microsoft.OSTCExtensions"
  tags                        = {}
  type                        = "VMAccessForLinux"
  type_handler_version        = "1.5"
  virtual_machine_id          = azurerm_linux_virtual_machine.vm_india.id
}
*/
